-- Refresh tokens for session renewal (access + refresh token flow)
-- Stores only the SHA-256 hash of the opaque refresh token, never the plain value.

CREATE TABLE refresh_token (
    rt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rt_token_hash VARCHAR(64) NOT NULL,
    rt_family_id UUID NOT NULL,
    rt_per_id INTEGER NOT NULL,
    rt_ctx_tipo VARCHAR(1),
    rt_ctx_entidad_id INTEGER,
    rt_ctx_prf_id INTEGER,
    rt_expira TIMESTAMP WITH TIME ZONE NOT NULL,
    rt_consumido TIMESTAMP WITH TIME ZONE,
    rt_revocado VARCHAR(1) NOT NULL DEFAULT 'N',
    rt_usr_crea INTEGER NOT NULL,
    rt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rt_est_crea VARCHAR(40) NOT NULL,
    rt_usr_mod INTEGER NOT NULL,
    rt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rt_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT uk_refresh_token_hash UNIQUE (rt_token_hash),
    CONSTRAINT fk_refresh_token_persona FOREIGN KEY (rt_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_token_perfil FOREIGN KEY (rt_ctx_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_token_usr_crea FOREIGN KEY (rt_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_refresh_token_usr_mod FOREIGN KEY (rt_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

CREATE INDEX idx_refresh_token_hash ON refresh_token(rt_token_hash);
CREATE INDEX idx_refresh_token_family ON refresh_token(rt_family_id);
CREATE INDEX idx_refresh_token_per ON refresh_token(rt_per_id);
CREATE INDEX idx_refresh_token_expira ON refresh_token(rt_expira);

COMMENT ON TABLE refresh_token IS 'Refresh tokens de sesion (solo hash SHA-256)';
COMMENT ON COLUMN refresh_token.rt_token_hash IS 'Hash SHA-256 (hex) del token opaco; nunca el valor en claro';
COMMENT ON COLUMN refresh_token.rt_family_id IS 'UUID de la sesion; agrupa la cadena de rotaciones';
COMMENT ON COLUMN refresh_token.rt_ctx_tipo IS 'Contexto: A=Administradora, C=Conjunto (null si aun no se elige contexto)';
COMMENT ON COLUMN refresh_token.rt_ctx_entidad_id IS 'ID de la entidad activa (administradora o conjunto)';
COMMENT ON COLUMN refresh_token.rt_ctx_prf_id IS 'ID del perfil activo';
COMMENT ON COLUMN refresh_token.rt_expira IS 'Fecha/hora de vencimiento absoluta del refresh';
COMMENT ON COLUMN refresh_token.rt_consumido IS 'Momento en que fue rotado (null si vigente)';
COMMENT ON COLUMN refresh_token.rt_revocado IS 'S=revocado, N=vigente';
