-- Password reset tokens for the forgot/reset password flow.
-- Only the SHA-256 hash of the opaque token is stored, never the plain value.

CREATE TABLE password_reset_token (
    prt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prt_token_hash VARCHAR(64) NOT NULL,
    prt_per_id INTEGER NOT NULL,
    prt_expira TIMESTAMP WITH TIME ZONE NOT NULL,
    prt_usado TIMESTAMP WITH TIME ZONE,
    prt_usr_crea INTEGER NOT NULL,
    prt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prt_est_crea VARCHAR(40) NOT NULL,
    prt_usr_mod INTEGER NOT NULL,
    prt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prt_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT uk_password_reset_token_hash UNIQUE (prt_token_hash),
    CONSTRAINT fk_password_reset_token_persona FOREIGN KEY (prt_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_password_reset_token_usr_crea FOREIGN KEY (prt_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_password_reset_token_usr_mod FOREIGN KEY (prt_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

CREATE INDEX idx_password_reset_token_hash ON password_reset_token(prt_token_hash);
CREATE INDEX idx_password_reset_token_per ON password_reset_token(prt_per_id);
CREATE INDEX idx_password_reset_token_expira ON password_reset_token(prt_expira);

COMMENT ON TABLE password_reset_token IS 'Tokens de restablecimiento de contrasena (solo hash SHA-256)';
COMMENT ON COLUMN password_reset_token.prt_token_hash IS 'Hash SHA-256 (hex) del token opaco; nunca el valor en claro';
COMMENT ON COLUMN password_reset_token.prt_per_id IS 'Persona duena del token';
COMMENT ON COLUMN password_reset_token.prt_expira IS 'Fecha/hora de vencimiento del token';
COMMENT ON COLUMN password_reset_token.prt_usado IS 'Momento en que el token fue consumido (null si disponible)';
