CREATE TABLE IF NOT EXISTS password_reset_token (
    prt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prt_token_hash VARCHAR(64) NOT NULL,
    prt_per_id INTEGER NOT NULL,
    prt_expira TIMESTAMP WITH TIME ZONE NOT NULL,
    prt_usado TIMESTAMP WITH TIME ZONE,
    prt_usr_crea INTEGER NOT NULL,
    prt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL,
    prt_est_crea VARCHAR(40) NOT NULL,
    prt_usr_mod INTEGER NOT NULL,
    prt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL,
    prt_est_mod VARCHAR(40) NOT NULL
);
