CREATE TABLE IF NOT EXISTS refresh_token (
    rt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rt_token_hash VARCHAR(64) NOT NULL,
    rt_family_id UUID NOT NULL,
    rt_per_id INTEGER NOT NULL,
    rt_ctx_tipo VARCHAR(1),
    rt_ctx_entidad_id INTEGER,
    rt_ctx_prf_id INTEGER,
    rt_expira TIMESTAMP WITH TIME ZONE NOT NULL,
    rt_consumido TIMESTAMP WITH TIME ZONE,
    rt_revocado VARCHAR(1) NOT NULL DEFAULT 'N',
    rt_usr_crea INTEGER NOT NULL,
    rt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL,
    rt_est_crea VARCHAR(40) NOT NULL,
    rt_usr_mod INTEGER NOT NULL,
    rt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL,
    rt_est_mod VARCHAR(40) NOT NULL
);
