info.app.name=ResiManager Backoffice
info.app.description=Sistema de gestion de condominios
info.app.version=1.0-SNAPSHOT
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@
