-- Relationship Tables (Junction/Association Tables)
-- These tables manage many-to-many relationships in the system

-- PersAdministradora (People belonging to Administradoras)
CREATE TABLE "PersAdministradora" (
    paid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pa_adm_id INTEGER NOT NULL,
    pa_per_id INTEGER NOT NULL,
    pa_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    pa_usr_crea INTEGER NOT NULL,
    pa_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pa_est_crea VARCHAR(40) NOT NULL,
    pa_usr_mod INTEGER NOT NULL,
    pa_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pa_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_persadm_adm FOREIGN KEY (pa_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_persadm_per FOREIGN KEY (pa_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_persadm_usr_crea FOREIGN KEY (pa_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_persadm_usr_mod FOREIGN KEY (pa_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_persadm_adm_per UNIQUE (pa_adm_id, pa_per_id)
);

COMMENT ON TABLE "PersAdministradora" IS 'Personas pertenecientes a administradoras';

-- PersConjunto (People belonging to Conjuntos)
CREATE TABLE "PersConjunto" (
    pcid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pc_conj_id INTEGER NOT NULL,
    pc_per_id INTEGER NOT NULL,
    pc_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    pc_usr_crea INTEGER NOT NULL,
    pc_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pc_est_crea VARCHAR(40) NOT NULL,
    pc_usr_mod INTEGER NOT NULL,
    pc_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pc_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_persconj_conj FOREIGN KEY (pc_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_persconj_per FOREIGN KEY (pc_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_persconj_usr_crea FOREIGN KEY (pc_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_persconj_usr_mod FOREIGN KEY (pc_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_persconj_conj_per UNIQUE (pc_conj_id, pc_per_id)
);

COMMENT ON TABLE "PersConjunto" IS 'Personas pertenecientes a conjuntos';

-- ConjAdministradora (Conjuntos managed by Administradoras with contract)
CREATE TABLE "ConjAdministradora" (
    caid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ca_adm_id INTEGER NOT NULL,
    ca_conj_id INTEGER NOT NULL,
    ca_ctt_id INTEGER NOT NULL,
    ca_fch_hor_desde TIMESTAMP WITH TIME ZONE NOT NULL,
    ca_fch_hor_hasta TIMESTAMP WITH TIME ZONE NOT NULL,
    ca_auto_renovar VARCHAR(1),
    ca_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    ca_usr_crea INTEGER NOT NULL,
    ca_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ca_est_crea VARCHAR(40) NOT NULL,
    ca_usr_mod INTEGER NOT NULL,
    ca_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ca_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_conjadm_adm FOREIGN KEY (ca_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjadm_conj FOREIGN KEY (ca_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjadm_ctt FOREIGN KEY (ca_ctt_id) REFERENCES "Contrato"(cttid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjadm_usr_crea FOREIGN KEY (ca_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjadm_usr_mod FOREIGN KEY (ca_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "ConjAdministradora" IS 'Conjuntos administrados por administradoras';

-- ConjPersAdministradora (People of Conjunto working for Administradora)
CREATE TABLE "ConjPersAdministradora" (
    cpaid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpa_adm_id INTEGER NOT NULL,
    cpa_per_id INTEGER NOT NULL,
    cpa_conj_id INTEGER NOT NULL,
    cpa_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    cpa_usr_crea INTEGER NOT NULL,
    cpa_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cpa_est_crea VARCHAR(40) NOT NULL,
    cpa_usr_mod INTEGER NOT NULL,
    cpa_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cpa_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_conjpersadm_adm FOREIGN KEY (cpa_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjpersadm_per FOREIGN KEY (cpa_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjpersadm_conj FOREIGN KEY (cpa_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjpersadm_usr_crea FOREIGN KEY (cpa_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjpersadm_usr_mod FOREIGN KEY (cpa_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "ConjPersAdministradora" IS 'Personas de conjunto en administradora';

-- PerfAdministradora (Profiles available in Administradora)
CREATE TABLE "PerfAdministradora" (
    pfaid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pfa_adm_id INTEGER NOT NULL,
    pfa_prf_id INTEGER NOT NULL,
    pfa_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    pfa_usr_crea INTEGER NOT NULL,
    pfa_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pfa_est_crea VARCHAR(40) NOT NULL,
    pfa_usr_mod INTEGER NOT NULL,
    pfa_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pfa_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_perfadm_adm FOREIGN KEY (pfa_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfadm_prf FOREIGN KEY (pfa_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfadm_usr_crea FOREIGN KEY (pfa_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfadm_usr_mod FOREIGN KEY (pfa_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_perfadm_adm_prf UNIQUE (pfa_adm_id, pfa_prf_id)
);

COMMENT ON TABLE "PerfAdministradora" IS 'Perfiles disponibles en administradoras';

-- PerfConjunto (Profiles available in Conjunto)
CREATE TABLE "PerfConjunto" (
    pfcid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pfc_conj_id INTEGER NOT NULL,
    pfc_prf_id INTEGER NOT NULL,
    pfc_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    pfc_usr_crea INTEGER NOT NULL,
    pfc_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pfc_est_crea VARCHAR(40) NOT NULL,
    pfc_usr_mod INTEGER NOT NULL,
    pfc_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pfc_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_perfconj_conj FOREIGN KEY (pfc_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfconj_prf FOREIGN KEY (pfc_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfconj_usr_crea FOREIGN KEY (pfc_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfconj_usr_mod FOREIGN KEY (pfc_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_perfconj_conj_prf UNIQUE (pfc_conj_id, pfc_prf_id)
);

COMMENT ON TABLE "PerfConjunto" IS 'Perfiles disponibles en conjuntos';

-- PerfPersAdministradora (Person-Profile assignment in Administradora)
CREATE TABLE "PerfPersAdministradora" (
    ppaid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ppa_adm_id INTEGER NOT NULL,
    ppa_per_id INTEGER NOT NULL,
    ppa_prf_id INTEGER NOT NULL,
    ppa_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    ppa_usr_crea INTEGER NOT NULL,
    ppa_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ppa_est_crea VARCHAR(40) NOT NULL,
    ppa_usr_mod INTEGER NOT NULL,
    ppa_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ppa_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_perfpersadm_adm FOREIGN KEY (ppa_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersadm_per FOREIGN KEY (ppa_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersadm_prf FOREIGN KEY (ppa_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersadm_usr_crea FOREIGN KEY (ppa_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersadm_usr_mod FOREIGN KEY (ppa_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_perfpersadm_adm_per_prf UNIQUE (ppa_adm_id, ppa_per_id, ppa_prf_id)
);

COMMENT ON TABLE "PerfPersAdministradora" IS 'Asignacion de perfiles a personas en administradoras';

-- PerfPersConjunto (Person-Profile assignment in Conjunto)
CREATE TABLE "PerfPersConjunto" (
    ppcid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ppc_conj_id INTEGER NOT NULL,
    ppc_per_id INTEGER NOT NULL,
    ppc_prf_id INTEGER NOT NULL,
    ppc_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    ppc_usr_crea INTEGER NOT NULL,
    ppc_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ppc_est_crea VARCHAR(40) NOT NULL,
    ppc_usr_mod INTEGER NOT NULL,
    ppc_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ppc_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_perfpersconj_conj FOREIGN KEY (ppc_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersconj_per FOREIGN KEY (ppc_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersconj_prf FOREIGN KEY (ppc_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersconj_usr_crea FOREIGN KEY (ppc_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfpersconj_usr_mod FOREIGN KEY (ppc_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_perfpersconj_conj_per_prf UNIQUE (ppc_conj_id, ppc_per_id, ppc_prf_id)
);

COMMENT ON TABLE "PerfPersConjunto" IS 'Asignacion de perfiles a personas en conjuntos';

-- ProptPropiedad (Property owners)
CREATE TABLE "ProptPropiedad" (
    prptid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prpt_pp_id INTEGER NOT NULL,
    prpt_per_id INTEGER NOT NULL,
    prpt_porc_participacion NUMERIC(5,4) NOT NULL,
    prpt_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    prpt_usr_crea INTEGER NOT NULL,
    prpt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prpt_est_crea VARCHAR(40) NOT NULL,
    prpt_usr_mod INTEGER NOT NULL,
    prpt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prpt_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_proptprop_pp FOREIGN KEY (prpt_pp_id) REFERENCES "Propiedad"(ppid) ON DELETE RESTRICT,
    CONSTRAINT fk_proptprop_per FOREIGN KEY (prpt_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_proptprop_usr_crea FOREIGN KEY (prpt_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_proptprop_usr_mod FOREIGN KEY (prpt_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "ProptPropiedad" IS 'Propietarios de propiedades';
COMMENT ON COLUMN "ProptPropiedad".prpt_porc_participacion IS 'Porcentaje de participacion (0.0000 a 1.0000)';
