-- Invitation System Tables
-- Manages UUID-based invitations with auto-expiration

-- Invitacion table (Invitations)
CREATE TABLE "Invitacion" (
    invid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_uuid UUID NOT NULL,
    inv_adm_id INTEGER,
    inv_conj_id INTEGER,
    inv_prf_id INTEGER NOT NULL,
    inv_per_id INTEGER,
    inv_email VARCHAR(80) NOT NULL,
    inv_nombre VARCHAR(80),
    inv_apellido VARCHAR(80),
    inv_fch_hor_envio TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inv_fch_hor_vencimiento TIMESTAMP WITH TIME ZONE NOT NULL,
    inv_fch_hor_aceptacion TIMESTAMP WITH TIME ZONE,
    inv_dias_validez INTEGER NOT NULL DEFAULT 7,
    inv_aceptada VARCHAR(1) NOT NULL DEFAULT 'N',
    inv_sts VARCHAR(1) NOT NULL DEFAULT 'P',
    inv_usr_crea INTEGER NOT NULL,
    inv_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inv_est_crea VARCHAR(40) NOT NULL,
    inv_usr_mod INTEGER NOT NULL,
    inv_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inv_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_invitacion_adm FOREIGN KEY (inv_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_invitacion_conj FOREIGN KEY (inv_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_invitacion_prf FOREIGN KEY (inv_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_invitacion_per FOREIGN KEY (inv_per_id) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_invitacion_usr_crea FOREIGN KEY (inv_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_invitacion_usr_mod FOREIGN KEY (inv_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_invitacion_uuid UNIQUE (inv_uuid),
    CONSTRAINT chk_invitacion_contexto CHECK (
        (inv_adm_id IS NOT NULL AND inv_conj_id IS NULL) OR
        (inv_adm_id IS NULL AND inv_conj_id IS NOT NULL)
    )
);

CREATE INDEX idx_invitacion_uuid ON "Invitacion"(inv_uuid);
CREATE INDEX idx_invitacion_email ON "Invitacion"(inv_email);
CREATE INDEX idx_invitacion_sts ON "Invitacion"(inv_sts);
CREATE INDEX idx_invitacion_vencimiento ON "Invitacion"(inv_fch_hor_vencimiento);

COMMENT ON TABLE "Invitacion" IS 'Sistema de invitaciones con UUID';
COMMENT ON COLUMN "Invitacion".inv_uuid IS 'Token UUID unico para la invitacion';
COMMENT ON COLUMN "Invitacion".inv_adm_id IS 'Administradora que invita (excluyente con conj_id)';
COMMENT ON COLUMN "Invitacion".inv_conj_id IS 'Conjunto que invita (excluyente con adm_id)';
COMMENT ON COLUMN "Invitacion".inv_prf_id IS 'Perfil asignado al aceptar';
COMMENT ON COLUMN "Invitacion".inv_per_id IS 'Persona resultante al aceptar';
COMMENT ON COLUMN "Invitacion".inv_dias_validez IS 'Dias de validez (default 7)';
COMMENT ON COLUMN "Invitacion".inv_aceptada IS 'Aceptada: S=Si, N=No';
COMMENT ON COLUMN "Invitacion".inv_sts IS 'Estatus: P=Pendiente, A=Aceptada, V=Vencida, E=Eliminada';
