-- Core Tables: Persona, Administradora, Conjunto, Propiedad, Perfil
-- Note: Using lowercase column names to match JPA entity mappings

-- Persona table (Users/People)
CREATE TABLE "Persona" (
    perid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    per_doc_ident VARCHAR(20) NOT NULL,
    per_nombre VARCHAR(80) NOT NULL,
    per_apellido VARCHAR(80) NOT NULL,
    per_tlf_cel VARCHAR(15) NOT NULL,
    per_email VARCHAR(80) NOT NULL,
    per_usuario VARCHAR(80),
    per_clave VARCHAR(80),
    per_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    per_usr_crea INTEGER NOT NULL,
    per_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    per_est_crea VARCHAR(40) NOT NULL,
    per_usr_mod INTEGER NOT NULL,
    per_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    per_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_persona_usr_crea FOREIGN KEY (per_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_persona_usr_mod FOREIGN KEY (per_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Persona" IS 'Informacion de personas';
COMMENT ON COLUMN "Persona".perid IS 'Identificador unico';
COMMENT ON COLUMN "Persona".per_doc_ident IS 'Documento de identidad';
COMMENT ON COLUMN "Persona".per_nombre IS 'Nombre';
COMMENT ON COLUMN "Persona".per_apellido IS 'Apellido';
COMMENT ON COLUMN "Persona".per_tlf_cel IS 'Telefono celular';
COMMENT ON COLUMN "Persona".per_email IS 'Correo electronico';
COMMENT ON COLUMN "Persona".per_usuario IS 'Nombre de usuario';
COMMENT ON COLUMN "Persona".per_clave IS 'Clave de acceso (hash)';
COMMENT ON COLUMN "Persona".per_sts IS 'Estatus: A=Activo, I=Inactivo, V=Vencido';

-- Administradora table (Management Companies)
CREATE TABLE "Administradora" (
    admid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adm_doc_ident VARCHAR(20) NOT NULL,
    adm_nombre VARCHAR(80) NOT NULL,
    adm_telefono VARCHAR(15) NOT NULL,
    adm_email VARCHAR(80) NOT NULL,
    adm_pers_contacto INTEGER NOT NULL,
    adm_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    adm_usr_crea INTEGER NOT NULL,
    adm_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adm_est_crea VARCHAR(40) NOT NULL,
    adm_usr_mod INTEGER NOT NULL,
    adm_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    adm_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_administradora_pers_contacto FOREIGN KEY (adm_pers_contacto) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_administradora_usr_crea FOREIGN KEY (adm_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_administradora_usr_mod FOREIGN KEY (adm_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Administradora" IS 'Informacion de compañias administradoras';
COMMENT ON COLUMN "Administradora".admid IS 'Identificador unico';
COMMENT ON COLUMN "Administradora".adm_doc_ident IS 'Documento de identidad';
COMMENT ON COLUMN "Administradora".adm_nombre IS 'Nombre de la administradora';
COMMENT ON COLUMN "Administradora".adm_pers_contacto IS 'Persona de contacto';
COMMENT ON COLUMN "Administradora".adm_sts IS 'Estatus: A=Activo, I=Inactivo';

-- Conjunto table (Condominiums/Residential Complexes)
CREATE TABLE "Conjunto" (
    conjid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conj_doc_ident VARCHAR(20) NOT NULL,
    conj_nombre VARCHAR(80) NOT NULL,
    conj_telefono VARCHAR(15) NOT NULL,
    conj_email VARCHAR(80) NOT NULL,
    conj_pers_contacto INTEGER NOT NULL,
    conj_area NUMERIC(15,5),
    conj_origen VARCHAR(1) NOT NULL,
    conj_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    conj_usr_crea INTEGER NOT NULL,
    conj_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    conj_est_crea VARCHAR(40) NOT NULL,
    conj_usr_mod INTEGER NOT NULL,
    conj_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    conj_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_conjunto_pers_contacto FOREIGN KEY (conj_pers_contacto) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjunto_usr_crea FOREIGN KEY (conj_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_conjunto_usr_mod FOREIGN KEY (conj_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Conjunto" IS 'Informacion de conjuntos residenciales';
COMMENT ON COLUMN "Conjunto".conjid IS 'Identificador unico';
COMMENT ON COLUMN "Conjunto".conj_area IS 'Area total del conjunto';
COMMENT ON COLUMN "Conjunto".conj_origen IS 'Origen: A=Administradora, C=Conjunto';
COMMENT ON COLUMN "Conjunto".conj_sts IS 'Estatus: A=Activo, I=Inactivo';

-- Perfil table (User Profiles/Roles)
CREATE TABLE "Perfil" (
    prfid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prf_nombre VARCHAR(80) NOT NULL,
    prf_descrip VARCHAR(120),
    prf_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    prf_usr_crea INTEGER NOT NULL,
    prf_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prf_est_crea VARCHAR(40) NOT NULL,
    prf_usr_mod INTEGER NOT NULL,
    prf_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    prf_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_perfil_usr_crea FOREIGN KEY (prf_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_perfil_usr_mod FOREIGN KEY (prf_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Perfil" IS 'Informacion de perfiles de usuario';
COMMENT ON COLUMN "Perfil".prfid IS 'Identificador unico';
COMMENT ON COLUMN "Perfil".prf_nombre IS 'Nombre del perfil';
COMMENT ON COLUMN "Perfil".prf_descrip IS 'Descripcion del perfil';

-- ClaseDePropiedad table (Property Classes)
CREATE TABLE "ClaseDePropiedad" (
    cdpid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cdp_conj_id INTEGER NOT NULL,
    cdp_nombre VARCHAR(80) NOT NULL,
    cdp_descrip VARCHAR(120),
    cdp_cantidad NUMERIC(10,4) NOT NULL,
    cdp_tipo_bien VARCHAR(1) NOT NULL,
    cdp_und_med VARCHAR(5) NOT NULL,
    cdp_tipo_ppd VARCHAR(2) NOT NULL,
    cdp_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    cdp_usr_crea INTEGER NOT NULL,
    cdp_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cdp_est_crea VARCHAR(40) NOT NULL,
    cdp_usr_mod INTEGER NOT NULL,
    cdp_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cdp_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_clase_propiedad_conj FOREIGN KEY (cdp_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_clase_propiedad_usr_crea FOREIGN KEY (cdp_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_clase_propiedad_usr_mod FOREIGN KEY (cdp_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "ClaseDePropiedad" IS 'Tipos de propiedades en un conjunto';
COMMENT ON COLUMN "ClaseDePropiedad".cdp_tipo_bien IS 'Tipo de bien: M=Mueble, I=Inmueble';
COMMENT ON COLUMN "ClaseDePropiedad".cdp_und_med IS 'Unidad de medida: UND, M2, etc';
COMMENT ON COLUMN "ClaseDePropiedad".cdp_tipo_ppd IS 'Tipo de propiedad: PR=Privada, CP=Colectiva Privada';

-- Propiedad table (Properties/Units)
CREATE TABLE "Propiedad" (
    ppid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pp_conj_id INTEGER NOT NULL,
    pp_cdp_id INTEGER NOT NULL,
    pp_numero VARCHAR(20) NOT NULL,
    pp_cantidad NUMERIC(10,4) NOT NULL,
    pp_coef_participacion NUMERIC(10,8) NOT NULL,
    pp_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    pp_usr_crea INTEGER NOT NULL,
    pp_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pp_est_crea VARCHAR(40) NOT NULL,
    pp_usr_mod INTEGER NOT NULL,
    pp_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pp_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_propiedad_conj FOREIGN KEY (pp_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_propiedad_cdp FOREIGN KEY (pp_cdp_id) REFERENCES "ClaseDePropiedad"(cdpid) ON DELETE RESTRICT,
    CONSTRAINT fk_propiedad_usr_crea FOREIGN KEY (pp_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_propiedad_usr_mod FOREIGN KEY (pp_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Propiedad" IS 'Propiedades individuales en un conjunto';
COMMENT ON COLUMN "Propiedad".pp_numero IS 'Numero de propiedad (apartamento, local, etc)';
COMMENT ON COLUMN "Propiedad".pp_coef_participacion IS 'Coeficiente de participacion en gastos comunes';

-- Moneda table (Currencies)
CREATE TABLE "Moneda" (
    mndid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mnd_conj_id INTEGER NOT NULL,
    mnd_nombre VARCHAR(80) NOT NULL,
    mnd_simbolo VARCHAR(10) NOT NULL,
    mnd_cod_iso VARCHAR(10) NOT NULL,
    mnd_und_fraccion VARCHAR(20) NOT NULL,
    mnd_tipo VARCHAR(1) NOT NULL,
    mnd_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    mnd_usr_crea INTEGER NOT NULL,
    mnd_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mnd_est_crea VARCHAR(40) NOT NULL,
    mnd_usr_mod INTEGER NOT NULL,
    mnd_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mnd_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_moneda_conj FOREIGN KEY (mnd_conj_id) REFERENCES "Conjunto"(conjid) ON DELETE RESTRICT,
    CONSTRAINT fk_moneda_usr_crea FOREIGN KEY (mnd_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_moneda_usr_mod FOREIGN KEY (mnd_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Moneda" IS 'Monedas utilizadas en conjuntos';
COMMENT ON COLUMN "Moneda".mnd_tipo IS 'Tipo: L=Local, R=Referencia, T=Transaccion';

-- Contrato table (Contracts)
CREATE TABLE "Contrato" (
    cttid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ctt_adm_id INTEGER NOT NULL,
    ctt_nombre VARCHAR(80),
    ctt_duracion INTEGER NOT NULL,
    ct_documento VARCHAR(120) NOT NULL,
    ctt_auto_renovar VARCHAR(1) NOT NULL,
    ctt_resindir_antes_de INTEGER NOT NULL,
    ctt_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    ctt_usr_crea INTEGER NOT NULL,
    ctt_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ctt_est_crea VARCHAR(40) NOT NULL,
    ctt_usr_mod INTEGER NOT NULL,
    ctt_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ctt_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_contrato_adm FOREIGN KEY (ctt_adm_id) REFERENCES "Administradora"(admid) ON DELETE RESTRICT,
    CONSTRAINT fk_contrato_usr_crea FOREIGN KEY (ctt_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_contrato_usr_mod FOREIGN KEY (ctt_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Contrato" IS 'Contratos de administracion';
COMMENT ON COLUMN "Contrato".ctt_duracion IS 'Duracion en meses';
COMMENT ON COLUMN "Contrato".ctt_resindir_antes_de IS 'Dias antes del vencimiento para rescindir';
