-- Security and Menu System Tables
-- Note: Using lowercase column names to match JPA entity mappings

-- Menu table (Top-level menus)
CREATE TABLE "Menu" (
    menuid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_nombre VARCHAR(80) NOT NULL,
    menu_descrip VARCHAR(120) NOT NULL,
    menu_posicion VARCHAR(1) NOT NULL,
    menu_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    menu_usr_crea INTEGER NOT NULL,
    menu_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    menu_est_crea VARCHAR(40) NOT NULL,
    menu_usr_mod INTEGER NOT NULL,
    menu_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    menu_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_menu_usr_crea FOREIGN KEY (menu_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_menu_usr_mod FOREIGN KEY (menu_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "Menu" IS 'Menus del sistema';
COMMENT ON COLUMN "Menu".menu_posicion IS 'Posicion: I=Izquierda, D=Derecha, T=Top, P=Pie';

-- MenuItem table (Menu items)
CREATE TABLE menu_item (
    mitid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mit_menuid INTEGER NOT NULL,
    mit_nombre VARCHAR(80) NOT NULL,
    mit_tipo VARCHAR(1) NOT NULL,
    mit_item_padre INTEGER NOT NULL,
    mit_orden INTEGER NOT NULL,
    mit_modid INTEGER,
    mit_opcionid INTEGER,
    mit_accionid INTEGER,
    mit_controlador VARCHAR(20),
    mit_metodo VARCHAR(20),
    mit_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    mit_usr_crea INTEGER NOT NULL,
    mit_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mit_est_crea VARCHAR(40) NOT NULL,
    mit_usr_mod INTEGER NOT NULL,
    mit_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mit_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_menuitem_menu FOREIGN KEY (mit_menuid) REFERENCES "Menu"(menuid) ON DELETE RESTRICT,
    CONSTRAINT fk_menuitem_usr_crea FOREIGN KEY (mit_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_menuitem_usr_mod FOREIGN KEY (mit_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE menu_item IS 'Items de menu';
COMMENT ON COLUMN menu_item.mit_tipo IS 'Tipo: A=Agrupa, S=Separador, O=Opcion';

-- Modulo table (Modules)
CREATE TABLE modulo (
    modid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mod_nombre VARCHAR(80) NOT NULL,
    mod_descrip VARCHAR(120),
    mod_nivel SMALLINT NOT NULL,
    mod_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    mod_usr_crea INTEGER NOT NULL,
    mod_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_est_crea VARCHAR(40) NOT NULL,
    mod_usr_mod INTEGER NOT NULL,
    mod_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_modulo_usr_crea FOREIGN KEY (mod_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_modulo_usr_mod FOREIGN KEY (mod_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE modulo IS 'Modulos del sistema';
COMMENT ON COLUMN modulo.mod_nivel IS 'Nivel jerarquico: 0=SuperAdmin, 1=Administradora, 2=Conjunto, 3=Propietario';

-- Opcion table (Options within modules)
CREATE TABLE opcion (
    opcid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opc_modid INTEGER NOT NULL,
    opc_nombre VARCHAR(80) NOT NULL,
    opc_descrip VARCHAR(120) NOT NULL,
    opc_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    opc_usr_crea INTEGER NOT NULL,
    opc_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opc_est_crea VARCHAR(40) NOT NULL,
    opc_usr_mod INTEGER NOT NULL,
    opc_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    opc_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_opcion_modulo FOREIGN KEY (opc_modid) REFERENCES modulo(modid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcion_usr_crea FOREIGN KEY (opc_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcion_usr_mod FOREIGN KEY (opc_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE opcion IS 'Opciones dentro de modulos';

-- Accion table (Actions: MNJ, INS, MOD, VIS, EL)
CREATE TABLE accion (
    accid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acc_nombre VARCHAR(80) NOT NULL,
    acc_descrip VARCHAR(120) NOT NULL,
    acc_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    acc_usr_crea INTEGER NOT NULL,
    acc_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acc_est_crea VARCHAR(40) NOT NULL,
    acc_usr_mod INTEGER NOT NULL,
    acc_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acc_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_accion_usr_crea FOREIGN KEY (acc_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_accion_usr_mod FOREIGN KEY (acc_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE accion IS 'Acciones posibles: MNJ, INS, MOD, VIS, EL';

-- AccOpcion table (Actions available for each option)
CREATE TABLE "AccOpcion" (
    aoid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ao_mod_id INTEGER NOT NULL,
    ao_opc_id INTEGER NOT NULL,
    ao_acc_id INTEGER NOT NULL,
    ao_cod_seg INTEGER NOT NULL,
    ao_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    ao_usr_crea INTEGER NOT NULL,
    ao_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ao_est_crea VARCHAR(40) NOT NULL,
    ao_usr_mod INTEGER NOT NULL,
    ao_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ao_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_accopcion_modulo FOREIGN KEY (ao_mod_id) REFERENCES modulo(modid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcion_opcion FOREIGN KEY (ao_opc_id) REFERENCES opcion(opcid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcion_accion FOREIGN KEY (ao_acc_id) REFERENCES accion(accid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcion_usr_crea FOREIGN KEY (ao_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcion_usr_mod FOREIGN KEY (ao_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT uk_accopcion_seg UNIQUE (ao_cod_seg)
);

COMMENT ON TABLE "AccOpcion" IS 'Acciones disponibles por opcion';
COMMENT ON COLUMN "AccOpcion".ao_cod_seg IS 'Codigo de seguridad unico';

-- ModPerfil table (Modules assigned to profiles)
CREATE TABLE "ModPerfil" (
    mpid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mp_prf_id INTEGER NOT NULL,
    mp_mod_id INTEGER NOT NULL,
    mp_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    mp_usr_crea INTEGER NOT NULL,
    mp_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mp_est_crea VARCHAR(40) NOT NULL,
    mp_usr_mod INTEGER NOT NULL,
    mp_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mp_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_modperfil_perfil FOREIGN KEY (mp_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_modperfil_modulo FOREIGN KEY (mp_mod_id) REFERENCES modulo(modid) ON DELETE RESTRICT,
    CONSTRAINT fk_modperfil_usr_crea FOREIGN KEY (mp_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_modperfil_usr_mod FOREIGN KEY (mp_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "ModPerfil" IS 'Modulos asignados a perfiles';

-- OpcPerfil table (Options assigned to profiles)
CREATE TABLE "OpcPerfil" (
    opid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op_prf_id INTEGER NOT NULL,
    op_mod_id INTEGER NOT NULL,
    op_opc_id INTEGER NOT NULL,
    op_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    op_usr_crea INTEGER NOT NULL,
    op_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    op_est_crea VARCHAR(40) NOT NULL,
    op_usr_mod INTEGER NOT NULL,
    op_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    op_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_opcperfil_perfil FOREIGN KEY (op_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcperfil_modulo FOREIGN KEY (op_mod_id) REFERENCES modulo(modid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcperfil_opcion FOREIGN KEY (op_opc_id) REFERENCES opcion(opcid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcperfil_usr_crea FOREIGN KEY (op_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_opcperfil_usr_mod FOREIGN KEY (op_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "OpcPerfil" IS 'Opciones asignadas a perfiles';

-- AccOpcPerfil table (Actions on options assigned to profiles)
CREATE TABLE "AccOpcPerfil" (
    aopid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aop_prf_id INTEGER NOT NULL,
    aop_mod_id INTEGER NOT NULL,
    aop_opc_id INTEGER NOT NULL,
    aop_acc_id INTEGER NOT NULL,
    aop_sts VARCHAR(1) NOT NULL DEFAULT 'A',
    aop_usr_crea INTEGER NOT NULL,
    aop_fch_hor_crea TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aop_est_crea VARCHAR(40) NOT NULL,
    aop_usr_mod INTEGER NOT NULL,
    aop_fch_hor_mod TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aop_est_mod VARCHAR(40) NOT NULL,
    CONSTRAINT fk_accopcperfil_perfil FOREIGN KEY (aop_prf_id) REFERENCES "Perfil"(prfid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcperfil_modulo FOREIGN KEY (aop_mod_id) REFERENCES modulo(modid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcperfil_opcion FOREIGN KEY (aop_opc_id) REFERENCES opcion(opcid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcperfil_accion FOREIGN KEY (aop_acc_id) REFERENCES accion(accid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcperfil_usr_crea FOREIGN KEY (aop_usr_crea) REFERENCES "Persona"(perid) ON DELETE RESTRICT,
    CONSTRAINT fk_accopcperfil_usr_mod FOREIGN KEY (aop_usr_mod) REFERENCES "Persona"(perid) ON DELETE RESTRICT
);

COMMENT ON TABLE "AccOpcPerfil" IS 'Acciones sobre opciones asignadas a perfiles (permisos finales)';
